baseURL = "http://localhost:1313/"
# baseURL = "https://cabear.com/hugo/"
languageCode = 'en-us'
title = 'My Hugo Swiper Site'
# theme = 'ananke'
theme = 'hugo-arcana'


[menu]

  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Single Swiper"
  url = "/single-swiper/"
  weight = 2

  [[menu.main]]
  name = "Gallery"
  url = "/gallery/"
  weight = 2


  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3
